blank_issues_enabled: false
contact_links:
  - name: 📖 提问的艺术
    url: https://opentyut.github.io/guide/how-to-ask
    about: 提问前请先阅读这份指南
  - name: 🌐 OpenTYUT 网站
    url: https://opentyut.github.io/
    about: 先看看网站上是否已经有你需要的信息
